services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - sql_data:/var/opt/mssql

  showcaseapi:
    build:
      context: .
      dockerfile: ShowcaseAPI/Dockerfile
    container_name: showcaseapi
    ports:
      - "5001:80"
    depends_on:
      - sqlserver
    env_file:
      - .env

  showcasefrontend:
    build:
      context: .
      dockerfile: ShowcaseFrontend/Dockerfile
      target: dev
    container_name: showcasefrontend
    ports:
      - "8080:80"
    depends_on:
      - showcaseapi
    environment:
      - API_BASE_URL=http://showcaseapi
    volumes:
      - ./ShowcaseFrontend:/app/ShowcaseFrontend
      - ~/.nuget/packages:/root/.nuget/packages:ro
    command: ["dotnet", "watch", "run", "--project", "/app/ShowcaseFrontend/ShowcaseFrontend.csproj", "--no-launch-profile", "--urls=http://0.0.0.0:80"]

volumes:
  sql_data:
