services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  showcasefrontend:
    build:
      context: .
      dockerfile: ShowcaseFrontend/Dockerfile
      target: "build"
    container_name: showcasefrontend
    ports:
      - "8080:80"
    depends_on:
      - showcaseapi
    environment:
      - API_BASE_URL=http://showcaseapi
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ./ShowcaseFrontend:/app/ShowcaseFrontend
      - ~/.nuget/packages:/root/.nuget/packages:ro
    command: ["dotnet", "watch", "run", "--project", "/app/ShowcaseFrontend/ShowcaseFrontend.csproj", "--no-launch-profile", "--urls=http://0.0.0.0:80"]
  
  showcaseapi:
    build:
      context: .
      dockerfile: ShowcaseAPI/Dockerfile
      target: "final"
    container_name: showcaseapi
    ports:
      - "5001:80"
    depends_on:
      - sqlserver
    env_file:
      - .env
    environment:
      - SQLSERVER_HOST=sqlserver
      - SQLSERVER_PORT=1433
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_ENVIRONMENT=Development

  showcaseapitesting:
    build:
      context: .
      dockerfile: ShowcaseApiTesting/Dockerfile
    container_name: showcaseapitesting
    depends_on:
      - showcaseapi
    volumes:
      - ./ShowcaseApiTesting/TestResults:/src/ShowcaseApiTesting/TestResults

volumes:
  sql_data:
